# Generated by Django 5.2.17 on 2026-08-12 10:27

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associates', '0011_level_commission_ledger'),
        ('commissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionentry',
            name='reference',
            field=models.CharField(blank=True, db_index=True, help_text='Transaction / sale reference (shared with wallet ledger)', max_length=80),
        ),
        migrations.AddField(
            model_name='commissionentry',
            name='sale_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Qualifying sale amount used for this calculation', max_digits=16),
        ),
        migrations.AddField(
            model_name='commissionentry',
            name='status',
            field=models.CharField(choices=[('credited', 'Credited'), ('skipped', 'Skipped'), ('voided', 'Voided')], db_index=True, default='credited', max_length=20),
        ),
        migrations.AlterField(
            model_name='commissionentry',
            name='source_associate',
            field=models.ForeignKey(blank=True, help_text='Buyer / associate whose sale generated this commission', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='generated_commissions', to='associates.associate'),
        ),
        migrations.AddConstraint(
            model_name='commissionentry',
            constraint=models.UniqueConstraint(condition=models.Q(('reference', ''), _negated=True), fields=('beneficiary', 'level', 'reference'), name='uniq_commission_beneficiary_level_reference'),
        ),
    ]
