# Generated by Django 5.2.17 on 2026-08-12 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0002_level_commission_ledger'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionentry',
            name='commission_month',
            field=models.DateField(blank=True, db_index=True, help_text='Month this recurring commission belongs to (1st of month)', null=True),
        ),
        migrations.AddField(
            model_name='commissionentry',
            name='growth_level',
            field=models.PositiveIntegerField(default=0, help_text="Earning user's Growth Level (direct qualifying sales) used for %"),
        ),
    ]
