# Generated by Django 5.2.17 on 2026-08-12 13:30

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0003_monthly_growth_roi'),
        ('investments', '0001_monthly_growth_roi'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionentry',
            name='investment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_entries', to='investments.investmentcontract'),
        ),
        migrations.AddField(
            model_name='commissionentry',
            name='month_index',
            field=models.PositiveSmallIntegerField(default=0, help_text='Installment number 1–48 for monthly ROI / growth commission'),
        ),
        migrations.AddField(
            model_name='commissionentry',
            name='monthly_return_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Monthly return base (₹2,200) for growth/ROI commissions', max_digits=16),
        ),
        migrations.AlterField(
            model_name='commissionentry',
            name='level',
            field=models.PositiveIntegerField(default=0, help_text='Network / upline depth (1–10). 0 = investor ROI credit.'),
        ),
        migrations.AlterField(
            model_name='commissionentry',
            name='sale_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Qualifying sale / investment principal used for this calculation', max_digits=16),
        ),
    ]
