# Generated by Django 5.2.16 on 2026-07-25 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycsubmission',
            name='aadhaar_document',
            field=models.FileField(blank=True, null=True, upload_to='kyc/aadhaar/'),
        ),
        migrations.AddField(
            model_name='kycsubmission',
            name='bank_document',
            field=models.FileField(blank=True, null=True, upload_to='kyc/bank/'),
        ),
        migrations.AddField(
            model_name='kycsubmission',
            name='pan_document',
            field=models.FileField(blank=True, null=True, upload_to='kyc/pan/'),
        ),
        migrations.AddField(
            model_name='kycsubmission',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/profile/'),
        ),
        migrations.AddField(
            model_name='kycsubmission',
            name='upi_id',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
