# Generated by Django 5.2.17 on 2026-08-12 13:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('associates', '0011_level_commission_ledger'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentContract',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('principal', models.DecimalField(decimal_places=2, default=Decimal('220000'), max_digits=16)),
                ('monthly_return', models.DecimalField(decimal_places=2, default=Decimal('2200.00'), max_digits=16)),
                ('months_total', models.PositiveSmallIntegerField(default=48)),
                ('months_paid', models.PositiveSmallIntegerField(default=0)),
                ('unit_index', models.PositiveIntegerField(default=1, help_text='Nth farmhouse unit under the same source_reference')),
                ('source_reference', models.CharField(db_index=True, max_length=80)),
                ('started_on', models.DateField(default=django.utils.timezone.localdate)),
                ('next_payout_on', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='active', max_length=20)),
                ('last_payout_on', models.DateField(blank=True, null=True)),
                ('associate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investment_contracts', to='associates.associate')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'next_payout_on'], name='investments_status_95c2a5_idx'), models.Index(fields=['associate', 'status'], name='investments_associa_fe9410_idx')],
                'constraints': [models.UniqueConstraint(fields=('source_reference', 'unit_index'), name='uniq_investment_source_unit')],
            },
        ),
    ]
