# Generated by Django 5.2.16 on 2026-07-28 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0008_reward_poster_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='require_leader_approval',
            field=models.BooleanField(default=False, help_text='If ON: new joins stay Pending until the team lead / sponsor approves. If OFF (default): join completes as Active and the member can open the dashboard immediately.'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='theme_accent',
            field=models.CharField(default='#149A56', max_length=20),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='theme_primary',
            field=models.CharField(default='#0B6B3A', max_length=20),
        ),
        migrations.AlterField(
            model_name='genealogysettings',
            name='leg_mode',
            field=models.CharField(choices=[('3', '3 Leg'), ('5', '5 Leg'), ('10', '10 Leg'), ('unlimited', 'Unlimited')], default='unlimited', help_text='How many direct legs (nodes) each associate may have under them.', max_length=20),
        ),
        migrations.AlterField(
            model_name='genealogysettings',
            name='max_legs',
            field=models.PositiveIntegerField(default=0, help_text='Direct capacity. Auto-filled from Leg mode (3/5/10). 0 = unlimited.'),
        ),
    ]
