# Generated by Django 5.2.16 on 2026-07-29 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0010_company_require_join_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysettings',
            name='require_leader_approval',
            field=models.BooleanField(default=False, help_text='Team Approvals toggle. If ON: show Team Approvals in the app, and new joins stay Pending until the lead approves. If OFF (default): hide Team Approvals; joins become Active immediately and open the dashboard.', verbose_name='Team Approvals (require leader approval)'),
        ),
    ]
