# Generated by Django 5.2.16 on 2026-07-29 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0011_company_team_approvals_help'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genealogysettings',
            name='leg_mode',
            field=models.CharField(choices=[('3', '3 Leg'), ('5', '5 Leg'), ('10', '10 Leg'), ('unlimited', 'Unlimited')], default='10', help_text='How many direct legs (nodes) each associate may have under them. Default: 10 Leg.', max_length=20),
        ),
        migrations.AlterField(
            model_name='genealogysettings',
            name='max_depth',
            field=models.PositiveIntegerField(default=10, help_text='Max tree depth from root (levels). Default 10. 0 = unlimited depth.'),
        ),
        migrations.AlterField(
            model_name='genealogysettings',
            name='max_legs',
            field=models.PositiveIntegerField(default=10, help_text='Direct capacity. Auto-filled from Leg mode (3/5/10). 0 = unlimited.'),
        ),
    ]
