# Generated by Django 5.2.16 on 2026-07-25 19:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Associate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('associate_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('referral_code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('sponsor_associate_id', models.CharField(blank=True, db_index=True, max_length=20)),
                ('placement_leg', models.PositiveIntegerField(default=0, help_text='Leg index under sponsor; 0 = auto')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('inactive', 'Inactive'), ('blocked', 'Blocked')], db_index=True, default='pending', max_length=20)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('state', models.CharField(blank=True, max_length=80)),
                ('country', models.CharField(default='India', max_length=80)),
                ('kyc_verified', models.BooleanField(default=False)),
                ('total_business', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('personal_business', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('direct_count', models.PositiveIntegerField(default=0)),
                ('direct_active_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('sponsor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='directs', to='associates.associate')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='associate', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'created_at'], name='associates__status_7f872c_idx'), models.Index(fields=['sponsor', 'status'], name='associates__sponsor_44f698_idx')],
            },
        ),
    ]
