# Generated by Django 5.2.16 on 2026-07-25 20:16

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='associate',
            name='card_tier',
            field=models.CharField(choices=[('platinum', 'Platinum Card'), ('silver', 'Silver Card'), ('gray', 'Gray Card')], db_index=True, default='gray', max_length=20),
        ),
        migrations.AddField(
            model_name='associate',
            name='flag_color',
            field=models.CharField(choices=[('green', 'Green Flag'), ('blue', 'Blue Flag'), ('pink', 'Pink Flag')], db_index=True, default='pink', max_length=20),
        ),
        migrations.AddField(
            model_name='associate',
            name='join_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16),
        ),
        migrations.AddField(
            model_name='associate',
            name='lead_reference',
            field=models.CharField(blank=True, db_index=True, help_text='Mandatory lead / introducer reference at joining', max_length=40),
        ),
        migrations.AlterField(
            model_name='associate',
            name='mobile',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='associate',
            index=models.Index(fields=['card_tier', 'flag_color'], name='associates__card_ti_a8613d_idx'),
        ),
        migrations.AddIndex(
            model_name='associate',
            index=models.Index(fields=['mobile'], name='associates__mobile_6ca2b2_idx'),
        ),
    ]
