# Generated by Django 5.2.16 on 2026-07-25 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associates', '0002_associate_card_tier_associate_flag_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='associate',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='associate',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending approval'), ('active', 'Active'), ('inactive', 'Inactive'), ('blocked', 'Blocked'), ('rejected', 'Rejected by leader')], db_index=True, default='pending', max_length=20),
        ),
    ]
