# Generated by Django 5.2.17 on 2026-08-12 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associates', '0010_login_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associate',
            name='login_password',
            field=models.CharField(blank=True, default='', help_text='Plaintext copy of the last password set at join or password change. Shown to staff/superadmin only. Login still uses Django’s hash — always set both via set_login_password().', max_length=128),
        ),
    ]
