# Generated by Django 5.2.17 on 2026-08-13 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('associates', '0011_level_commission_ledger'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedAssociate',
            fields=[
            ],
            options={
                'verbose_name': 'Deleted / deactivated account',
                'verbose_name_plural': 'Deleted / deactivated accounts',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('associates.associate',),
        ),
    ]
