/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AppBusinessReportRouteImport } from './routes/_app/business-report'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppGenealogyRouteImport } from './routes/_app/genealogy'
import { Route as AppKnowledgeRouteImport } from './routes/_app/knowledge'
import { Route as AppDepositCompleteRouteImport } from './routes/_app/deposit.complete'
import { Route as AppDepositPendingRouteImport } from './routes/_app/deposit.pending'
import { Route as AppDepositRejectedRouteImport } from './routes/_app/deposit.rejected'
import { Route as AppFundAdminHistoryRouteImport } from './routes/_app/fund.admin-history'
import { Route as AppFundTransferRouteImport } from './routes/_app/fund.transfer'
import { Route as AppFundUserHistoryRouteImport } from './routes/_app/fund.user-history'
import { Route as AppFundWalletsRouteImport } from './routes/_app/fund.wallets'
import { Route as AppGenealogyIndexRouteImport } from './routes/_app/genealogy.index'
import { Route as AppGenealogyShiftRouteImport } from './routes/_app/genealogy.shift'
import { Route as AppIncomeAdminChargesRouteImport } from './routes/_app/income.admin-charges'
import { Route as AppIncomeReferralRouteImport } from './routes/_app/income.referral'
import { Route as AppIncomeRewardRouteImport } from './routes/_app/income.reward'
import { Route as AppIncomeRoiRouteImport } from './routes/_app/income.roi'
import { Route as AppIncomeSpProfitRouteImport } from './routes/_app/income.sp-profit'
import { Route as AppKycApprovedRouteImport } from './routes/_app/kyc.approved'
import { Route as AppKycPendingRouteImport } from './routes/_app/kyc.pending'
import { Route as AppKycRejectedRouteImport } from './routes/_app/kyc.rejected'
import { Route as AppPlansDirectRouteImport } from './routes/_app/plans.direct'
import { Route as AppPlansPerformanceRouteImport } from './routes/_app/plans.performance'
import { Route as AppPlansRewardsRouteImport } from './routes/_app/plans.rewards'
import { Route as AppRbacAuditRouteImport } from './routes/_app/rbac.audit'
import { Route as AppRbacProfileRouteImport } from './routes/_app/rbac.profile'
import { Route as AppRbacRolesRouteImport } from './routes/_app/rbac.roles'
import { Route as AppRbacStaffRouteImport } from './routes/_app/rbac.staff'
import { Route as AppSettingsHelpRouteImport } from './routes/_app/settings.help'
import { Route as AppSettingsNewsRouteImport } from './routes/_app/settings.news'
import { Route as AppSettingsQrWalletRouteImport } from './routes/_app/settings.qr-wallet'
import { Route as AppTeamApprovalsRouteImport } from './routes/_app/team.approvals'
import { Route as AppUsersAssociateIdRouteImport } from './routes/_app/users.$associateId'
import { Route as AppUsersActiveRouteImport } from './routes/_app/users.active'
import { Route as AppUsersAllRouteImport } from './routes/_app/users.all'
import { Route as AppUsersBlockedRouteImport } from './routes/_app/users.blocked'
import { Route as AppUsersInactiveRouteImport } from './routes/_app/users.inactive'
import { Route as AppUsersLevelsRouteImport } from './routes/_app/users.levels'
import { Route as AppUsersMyRouteImport } from './routes/_app/users.my'
import { Route as AppUsersRewardsRouteImport } from './routes/_app/users.rewards'
import { Route as AppUsersTeamRouteImport } from './routes/_app/users.team'
import { Route as AppWithdrawCompletedRouteImport } from './routes/_app/withdraw.completed'
import { Route as AppWithdrawPendingRouteImport } from './routes/_app/withdraw.pending'
import { Route as AppWithdrawRejectedRouteImport } from './routes/_app/withdraw.rejected'
import { Route as AppUsersTeamIndexRouteImport } from './routes/_app/users.team.index'
import { Route as AppUsersTeamLevelLevelRouteImport } from './routes/_app/users.team.level.$level'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRoute = PartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBusinessReportRoute = AppBusinessReportRouteImport.update({
  id: '/business-report',
  path: '/business-report',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppGenealogyRoute = AppGenealogyRouteImport.update({
  id: '/genealogy',
  path: '/genealogy',
  getParentRoute: () => AppRoute,
} as any)
const AppKnowledgeRoute = AppKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AppRoute,
} as any)
const AppDepositCompleteRoute = AppDepositCompleteRouteImport.update({
  id: '/deposit/complete',
  path: '/deposit/complete',
  getParentRoute: () => AppRoute,
} as any)
const AppDepositPendingRoute = AppDepositPendingRouteImport.update({
  id: '/deposit/pending',
  path: '/deposit/pending',
  getParentRoute: () => AppRoute,
} as any)
const AppDepositRejectedRoute = AppDepositRejectedRouteImport.update({
  id: '/deposit/rejected',
  path: '/deposit/rejected',
  getParentRoute: () => AppRoute,
} as any)
const AppFundAdminHistoryRoute = AppFundAdminHistoryRouteImport.update({
  id: '/fund/admin-history',
  path: '/fund/admin-history',
  getParentRoute: () => AppRoute,
} as any)
const AppFundTransferRoute = AppFundTransferRouteImport.update({
  id: '/fund/transfer',
  path: '/fund/transfer',
  getParentRoute: () => AppRoute,
} as any)
const AppFundUserHistoryRoute = AppFundUserHistoryRouteImport.update({
  id: '/fund/user-history',
  path: '/fund/user-history',
  getParentRoute: () => AppRoute,
} as any)
const AppFundWalletsRoute = AppFundWalletsRouteImport.update({
  id: '/fund/wallets',
  path: '/fund/wallets',
  getParentRoute: () => AppRoute,
} as any)
const AppGenealogyIndexRoute = AppGenealogyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppGenealogyRoute,
} as any)
const AppGenealogyShiftRoute = AppGenealogyShiftRouteImport.update({
  id: '/shift',
  path: '/shift',
  getParentRoute: () => AppGenealogyRoute,
} as any)
const AppIncomeAdminChargesRoute = AppIncomeAdminChargesRouteImport.update({
  id: '/income/admin-charges',
  path: '/income/admin-charges',
  getParentRoute: () => AppRoute,
} as any)
const AppIncomeReferralRoute = AppIncomeReferralRouteImport.update({
  id: '/income/referral',
  path: '/income/referral',
  getParentRoute: () => AppRoute,
} as any)
const AppIncomeRewardRoute = AppIncomeRewardRouteImport.update({
  id: '/income/reward',
  path: '/income/reward',
  getParentRoute: () => AppRoute,
} as any)
const AppIncomeRoiRoute = AppIncomeRoiRouteImport.update({
  id: '/income/roi',
  path: '/income/roi',
  getParentRoute: () => AppRoute,
} as any)
const AppIncomeSpProfitRoute = AppIncomeSpProfitRouteImport.update({
  id: '/income/sp-profit',
  path: '/income/sp-profit',
  getParentRoute: () => AppRoute,
} as any)
const AppKycApprovedRoute = AppKycApprovedRouteImport.update({
  id: '/kyc/approved',
  path: '/kyc/approved',
  getParentRoute: () => AppRoute,
} as any)
const AppKycPendingRoute = AppKycPendingRouteImport.update({
  id: '/kyc/pending',
  path: '/kyc/pending',
  getParentRoute: () => AppRoute,
} as any)
const AppKycRejectedRoute = AppKycRejectedRouteImport.update({
  id: '/kyc/rejected',
  path: '/kyc/rejected',
  getParentRoute: () => AppRoute,
} as any)
const AppPlansDirectRoute = AppPlansDirectRouteImport.update({
  id: '/plans/direct',
  path: '/plans/direct',
  getParentRoute: () => AppRoute,
} as any)
const AppPlansPerformanceRoute = AppPlansPerformanceRouteImport.update({
  id: '/plans/performance',
  path: '/plans/performance',
  getParentRoute: () => AppRoute,
} as any)
const AppPlansRewardsRoute = AppPlansRewardsRouteImport.update({
  id: '/plans/rewards',
  path: '/plans/rewards',
  getParentRoute: () => AppRoute,
} as any)
const AppRbacAuditRoute = AppRbacAuditRouteImport.update({
  id: '/rbac/audit',
  path: '/rbac/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppRbacProfileRoute = AppRbacProfileRouteImport.update({
  id: '/rbac/profile',
  path: '/rbac/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppRbacRolesRoute = AppRbacRolesRouteImport.update({
  id: '/rbac/roles',
  path: '/rbac/roles',
  getParentRoute: () => AppRoute,
} as any)
const AppRbacStaffRoute = AppRbacStaffRouteImport.update({
  id: '/rbac/staff',
  path: '/rbac/staff',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsHelpRoute = AppSettingsHelpRouteImport.update({
  id: '/settings/help',
  path: '/settings/help',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsNewsRoute = AppSettingsNewsRouteImport.update({
  id: '/settings/news',
  path: '/settings/news',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsQrWalletRoute = AppSettingsQrWalletRouteImport.update({
  id: '/settings/qr-wallet',
  path: '/settings/qr-wallet',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamApprovalsRoute = AppTeamApprovalsRouteImport.update({
  id: '/team/approvals',
  path: '/team/approvals',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersAssociateIdRoute = AppUsersAssociateIdRouteImport.update({
  id: '/users/$associateId',
  path: '/users/$associateId',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersActiveRoute = AppUsersActiveRouteImport.update({
  id: '/users/active',
  path: '/users/active',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersAllRoute = AppUsersAllRouteImport.update({
  id: '/users/all',
  path: '/users/all',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersBlockedRoute = AppUsersBlockedRouteImport.update({
  id: '/users/blocked',
  path: '/users/blocked',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersInactiveRoute = AppUsersInactiveRouteImport.update({
  id: '/users/inactive',
  path: '/users/inactive',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersLevelsRoute = AppUsersLevelsRouteImport.update({
  id: '/users/levels',
  path: '/users/levels',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersMyRoute = AppUsersMyRouteImport.update({
  id: '/users/my',
  path: '/users/my',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRewardsRoute = AppUsersRewardsRouteImport.update({
  id: '/users/rewards',
  path: '/users/rewards',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersTeamRoute = AppUsersTeamRouteImport.update({
  id: '/users/team',
  path: '/users/team',
  getParentRoute: () => AppRoute,
} as any)
const AppWithdrawCompletedRoute = AppWithdrawCompletedRouteImport.update({
  id: '/withdraw/completed',
  path: '/withdraw/completed',
  getParentRoute: () => AppRoute,
} as any)
const AppWithdrawPendingRoute = AppWithdrawPendingRouteImport.update({
  id: '/withdraw/pending',
  path: '/withdraw/pending',
  getParentRoute: () => AppRoute,
} as any)
const AppWithdrawRejectedRoute = AppWithdrawRejectedRouteImport.update({
  id: '/withdraw/rejected',
  path: '/withdraw/rejected',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersTeamIndexRoute = AppUsersTeamIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppUsersTeamRoute,
} as any)
const AppUsersTeamLevelLevelRoute = AppUsersTeamLevelLevelRouteImport.update({
  id: '/level/$level',
  path: '/level/$level',
  getParentRoute: () => AppUsersTeamRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/partner': typeof PartnerRoute
  '/register': typeof RegisterRoute
  '/business-report': typeof AppBusinessReportRoute
  '/dashboard': typeof AppDashboardRoute
  '/genealogy': typeof AppGenealogyRouteWithChildren
  '/knowledge': typeof AppKnowledgeRoute
  '/deposit/complete': typeof AppDepositCompleteRoute
  '/deposit/pending': typeof AppDepositPendingRoute
  '/deposit/rejected': typeof AppDepositRejectedRoute
  '/fund/admin-history': typeof AppFundAdminHistoryRoute
  '/fund/transfer': typeof AppFundTransferRoute
  '/fund/user-history': typeof AppFundUserHistoryRoute
  '/fund/wallets': typeof AppFundWalletsRoute
  '/genealogy/shift': typeof AppGenealogyShiftRoute
  '/income/admin-charges': typeof AppIncomeAdminChargesRoute
  '/income/referral': typeof AppIncomeReferralRoute
  '/income/reward': typeof AppIncomeRewardRoute
  '/income/roi': typeof AppIncomeRoiRoute
  '/income/sp-profit': typeof AppIncomeSpProfitRoute
  '/kyc/approved': typeof AppKycApprovedRoute
  '/kyc/pending': typeof AppKycPendingRoute
  '/kyc/rejected': typeof AppKycRejectedRoute
  '/plans/direct': typeof AppPlansDirectRoute
  '/plans/performance': typeof AppPlansPerformanceRoute
  '/plans/rewards': typeof AppPlansRewardsRoute
  '/rbac/audit': typeof AppRbacAuditRoute
  '/rbac/profile': typeof AppRbacProfileRoute
  '/rbac/roles': typeof AppRbacRolesRoute
  '/rbac/staff': typeof AppRbacStaffRoute
  '/settings/help': typeof AppSettingsHelpRoute
  '/settings/news': typeof AppSettingsNewsRoute
  '/settings/qr-wallet': typeof AppSettingsQrWalletRoute
  '/team/approvals': typeof AppTeamApprovalsRoute
  '/users/$associateId': typeof AppUsersAssociateIdRoute
  '/users/active': typeof AppUsersActiveRoute
  '/users/all': typeof AppUsersAllRoute
  '/users/blocked': typeof AppUsersBlockedRoute
  '/users/inactive': typeof AppUsersInactiveRoute
  '/users/levels': typeof AppUsersLevelsRoute
  '/users/my': typeof AppUsersMyRoute
  '/users/rewards': typeof AppUsersRewardsRoute
  '/users/team': typeof AppUsersTeamRouteWithChildren
  '/withdraw/completed': typeof AppWithdrawCompletedRoute
  '/withdraw/pending': typeof AppWithdrawPendingRoute
  '/withdraw/rejected': typeof AppWithdrawRejectedRoute
  '/genealogy/': typeof AppGenealogyIndexRoute
  '/users/team/': typeof AppUsersTeamIndexRoute
  '/users/team/level/$level': typeof AppUsersTeamLevelLevelRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/partner': typeof PartnerRoute
  '/register': typeof RegisterRoute
  '/business-report': typeof AppBusinessReportRoute
  '/dashboard': typeof AppDashboardRoute
  '/knowledge': typeof AppKnowledgeRoute
  '/deposit/complete': typeof AppDepositCompleteRoute
  '/deposit/pending': typeof AppDepositPendingRoute
  '/deposit/rejected': typeof AppDepositRejectedRoute
  '/fund/admin-history': typeof AppFundAdminHistoryRoute
  '/fund/transfer': typeof AppFundTransferRoute
  '/fund/user-history': typeof AppFundUserHistoryRoute
  '/fund/wallets': typeof AppFundWalletsRoute
  '/genealogy/shift': typeof AppGenealogyShiftRoute
  '/income/admin-charges': typeof AppIncomeAdminChargesRoute
  '/income/referral': typeof AppIncomeReferralRoute
  '/income/reward': typeof AppIncomeRewardRoute
  '/income/roi': typeof AppIncomeRoiRoute
  '/income/sp-profit': typeof AppIncomeSpProfitRoute
  '/kyc/approved': typeof AppKycApprovedRoute
  '/kyc/pending': typeof AppKycPendingRoute
  '/kyc/rejected': typeof AppKycRejectedRoute
  '/plans/direct': typeof AppPlansDirectRoute
  '/plans/performance': typeof AppPlansPerformanceRoute
  '/plans/rewards': typeof AppPlansRewardsRoute
  '/rbac/audit': typeof AppRbacAuditRoute
  '/rbac/profile': typeof AppRbacProfileRoute
  '/rbac/roles': typeof AppRbacRolesRoute
  '/rbac/staff': typeof AppRbacStaffRoute
  '/settings/help': typeof AppSettingsHelpRoute
  '/settings/news': typeof AppSettingsNewsRoute
  '/settings/qr-wallet': typeof AppSettingsQrWalletRoute
  '/team/approvals': typeof AppTeamApprovalsRoute
  '/users/$associateId': typeof AppUsersAssociateIdRoute
  '/users/active': typeof AppUsersActiveRoute
  '/users/all': typeof AppUsersAllRoute
  '/users/blocked': typeof AppUsersBlockedRoute
  '/users/inactive': typeof AppUsersInactiveRoute
  '/users/levels': typeof AppUsersLevelsRoute
  '/users/my': typeof AppUsersMyRoute
  '/users/rewards': typeof AppUsersRewardsRoute
  '/withdraw/completed': typeof AppWithdrawCompletedRoute
  '/withdraw/pending': typeof AppWithdrawPendingRoute
  '/withdraw/rejected': typeof AppWithdrawRejectedRoute
  '/genealogy': typeof AppGenealogyIndexRoute
  '/users/team': typeof AppUsersTeamIndexRoute
  '/users/team/level/$level': typeof AppUsersTeamLevelLevelRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/partner': typeof PartnerRoute
  '/register': typeof RegisterRoute
  '/_app/business-report': typeof AppBusinessReportRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/genealogy': typeof AppGenealogyRouteWithChildren
  '/_app/knowledge': typeof AppKnowledgeRoute
  '/_app/deposit/complete': typeof AppDepositCompleteRoute
  '/_app/deposit/pending': typeof AppDepositPendingRoute
  '/_app/deposit/rejected': typeof AppDepositRejectedRoute
  '/_app/fund/admin-history': typeof AppFundAdminHistoryRoute
  '/_app/fund/transfer': typeof AppFundTransferRoute
  '/_app/fund/user-history': typeof AppFundUserHistoryRoute
  '/_app/fund/wallets': typeof AppFundWalletsRoute
  '/_app/genealogy/shift': typeof AppGenealogyShiftRoute
  '/_app/income/admin-charges': typeof AppIncomeAdminChargesRoute
  '/_app/income/referral': typeof AppIncomeReferralRoute
  '/_app/income/reward': typeof AppIncomeRewardRoute
  '/_app/income/roi': typeof AppIncomeRoiRoute
  '/_app/income/sp-profit': typeof AppIncomeSpProfitRoute
  '/_app/kyc/approved': typeof AppKycApprovedRoute
  '/_app/kyc/pending': typeof AppKycPendingRoute
  '/_app/kyc/rejected': typeof AppKycRejectedRoute
  '/_app/plans/direct': typeof AppPlansDirectRoute
  '/_app/plans/performance': typeof AppPlansPerformanceRoute
  '/_app/plans/rewards': typeof AppPlansRewardsRoute
  '/_app/rbac/audit': typeof AppRbacAuditRoute
  '/_app/rbac/profile': typeof AppRbacProfileRoute
  '/_app/rbac/roles': typeof AppRbacRolesRoute
  '/_app/rbac/staff': typeof AppRbacStaffRoute
  '/_app/settings/help': typeof AppSettingsHelpRoute
  '/_app/settings/news': typeof AppSettingsNewsRoute
  '/_app/settings/qr-wallet': typeof AppSettingsQrWalletRoute
  '/_app/team/approvals': typeof AppTeamApprovalsRoute
  '/_app/users/$associateId': typeof AppUsersAssociateIdRoute
  '/_app/users/active': typeof AppUsersActiveRoute
  '/_app/users/all': typeof AppUsersAllRoute
  '/_app/users/blocked': typeof AppUsersBlockedRoute
  '/_app/users/inactive': typeof AppUsersInactiveRoute
  '/_app/users/levels': typeof AppUsersLevelsRoute
  '/_app/users/my': typeof AppUsersMyRoute
  '/_app/users/rewards': typeof AppUsersRewardsRoute
  '/_app/users/team': typeof AppUsersTeamRouteWithChildren
  '/_app/withdraw/completed': typeof AppWithdrawCompletedRoute
  '/_app/withdraw/pending': typeof AppWithdrawPendingRoute
  '/_app/withdraw/rejected': typeof AppWithdrawRejectedRoute
  '/_app/genealogy/': typeof AppGenealogyIndexRoute
  '/_app/users/team/': typeof AppUsersTeamIndexRoute
  '/_app/users/team/level/$level': typeof AppUsersTeamLevelLevelRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/partner'
    | '/register'
    | '/business-report'
    | '/dashboard'
    | '/genealogy'
    | '/knowledge'
    | '/deposit/complete'
    | '/deposit/pending'
    | '/deposit/rejected'
    | '/fund/admin-history'
    | '/fund/transfer'
    | '/fund/user-history'
    | '/fund/wallets'
    | '/genealogy/shift'
    | '/income/admin-charges'
    | '/income/referral'
    | '/income/reward'
    | '/income/roi'
    | '/income/sp-profit'
    | '/kyc/approved'
    | '/kyc/pending'
    | '/kyc/rejected'
    | '/plans/direct'
    | '/plans/performance'
    | '/plans/rewards'
    | '/rbac/audit'
    | '/rbac/profile'
    | '/rbac/roles'
    | '/rbac/staff'
    | '/settings/help'
    | '/settings/news'
    | '/settings/qr-wallet'
    | '/team/approvals'
    | '/users/$associateId'
    | '/users/active'
    | '/users/all'
    | '/users/blocked'
    | '/users/inactive'
    | '/users/levels'
    | '/users/my'
    | '/users/rewards'
    | '/users/team'
    | '/withdraw/completed'
    | '/withdraw/pending'
    | '/withdraw/rejected'
    | '/genealogy/'
    | '/users/team/'
    | '/users/team/level/$level'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/partner'
    | '/register'
    | '/business-report'
    | '/dashboard'
    | '/knowledge'
    | '/deposit/complete'
    | '/deposit/pending'
    | '/deposit/rejected'
    | '/fund/admin-history'
    | '/fund/transfer'
    | '/fund/user-history'
    | '/fund/wallets'
    | '/genealogy/shift'
    | '/income/admin-charges'
    | '/income/referral'
    | '/income/reward'
    | '/income/roi'
    | '/income/sp-profit'
    | '/kyc/approved'
    | '/kyc/pending'
    | '/kyc/rejected'
    | '/plans/direct'
    | '/plans/performance'
    | '/plans/rewards'
    | '/rbac/audit'
    | '/rbac/profile'
    | '/rbac/roles'
    | '/rbac/staff'
    | '/settings/help'
    | '/settings/news'
    | '/settings/qr-wallet'
    | '/team/approvals'
    | '/users/$associateId'
    | '/users/active'
    | '/users/all'
    | '/users/blocked'
    | '/users/inactive'
    | '/users/levels'
    | '/users/my'
    | '/users/rewards'
    | '/withdraw/completed'
    | '/withdraw/pending'
    | '/withdraw/rejected'
    | '/genealogy'
    | '/users/team'
    | '/users/team/level/$level'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/partner'
    | '/register'
    | '/_app/business-report'
    | '/_app/dashboard'
    | '/_app/genealogy'
    | '/_app/knowledge'
    | '/_app/deposit/complete'
    | '/_app/deposit/pending'
    | '/_app/deposit/rejected'
    | '/_app/fund/admin-history'
    | '/_app/fund/transfer'
    | '/_app/fund/user-history'
    | '/_app/fund/wallets'
    | '/_app/genealogy/shift'
    | '/_app/income/admin-charges'
    | '/_app/income/referral'
    | '/_app/income/reward'
    | '/_app/income/roi'
    | '/_app/income/sp-profit'
    | '/_app/kyc/approved'
    | '/_app/kyc/pending'
    | '/_app/kyc/rejected'
    | '/_app/plans/direct'
    | '/_app/plans/performance'
    | '/_app/plans/rewards'
    | '/_app/rbac/audit'
    | '/_app/rbac/profile'
    | '/_app/rbac/roles'
    | '/_app/rbac/staff'
    | '/_app/settings/help'
    | '/_app/settings/news'
    | '/_app/settings/qr-wallet'
    | '/_app/team/approvals'
    | '/_app/users/$associateId'
    | '/_app/users/active'
    | '/_app/users/all'
    | '/_app/users/blocked'
    | '/_app/users/inactive'
    | '/_app/users/levels'
    | '/_app/users/my'
    | '/_app/users/rewards'
    | '/_app/users/team'
    | '/_app/withdraw/completed'
    | '/_app/withdraw/pending'
    | '/_app/withdraw/rejected'
    | '/_app/genealogy/'
    | '/_app/users/team/'
    | '/_app/users/team/level/$level'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  PartnerRoute: typeof PartnerRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/business-report': {
      id: '/_app/business-report'
      path: '/business-report'
      fullPath: '/business-report'
      preLoaderRoute: typeof AppBusinessReportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/genealogy': {
      id: '/_app/genealogy'
      path: '/genealogy'
      fullPath: '/genealogy'
      preLoaderRoute: typeof AppGenealogyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/knowledge': {
      id: '/_app/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof AppKnowledgeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/deposit/complete': {
      id: '/_app/deposit/complete'
      path: '/deposit/complete'
      fullPath: '/deposit/complete'
      preLoaderRoute: typeof AppDepositCompleteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/deposit/pending': {
      id: '/_app/deposit/pending'
      path: '/deposit/pending'
      fullPath: '/deposit/pending'
      preLoaderRoute: typeof AppDepositPendingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/deposit/rejected': {
      id: '/_app/deposit/rejected'
      path: '/deposit/rejected'
      fullPath: '/deposit/rejected'
      preLoaderRoute: typeof AppDepositRejectedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fund/admin-history': {
      id: '/_app/fund/admin-history'
      path: '/fund/admin-history'
      fullPath: '/fund/admin-history'
      preLoaderRoute: typeof AppFundAdminHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fund/transfer': {
      id: '/_app/fund/transfer'
      path: '/fund/transfer'
      fullPath: '/fund/transfer'
      preLoaderRoute: typeof AppFundTransferRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fund/user-history': {
      id: '/_app/fund/user-history'
      path: '/fund/user-history'
      fullPath: '/fund/user-history'
      preLoaderRoute: typeof AppFundUserHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fund/wallets': {
      id: '/_app/fund/wallets'
      path: '/fund/wallets'
      fullPath: '/fund/wallets'
      preLoaderRoute: typeof AppFundWalletsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/genealogy/': {
      id: '/_app/genealogy/'
      path: '/'
      fullPath: '/genealogy/'
      preLoaderRoute: typeof AppGenealogyIndexRouteImport
      parentRoute: typeof AppGenealogyRoute
    }
    '/_app/genealogy/shift': {
      id: '/_app/genealogy/shift'
      path: '/shift'
      fullPath: '/genealogy/shift'
      preLoaderRoute: typeof AppGenealogyShiftRouteImport
      parentRoute: typeof AppGenealogyRoute
    }
    '/_app/income/admin-charges': {
      id: '/_app/income/admin-charges'
      path: '/income/admin-charges'
      fullPath: '/income/admin-charges'
      preLoaderRoute: typeof AppIncomeAdminChargesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/income/referral': {
      id: '/_app/income/referral'
      path: '/income/referral'
      fullPath: '/income/referral'
      preLoaderRoute: typeof AppIncomeReferralRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/income/reward': {
      id: '/_app/income/reward'
      path: '/income/reward'
      fullPath: '/income/reward'
      preLoaderRoute: typeof AppIncomeRewardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/income/roi': {
      id: '/_app/income/roi'
      path: '/income/roi'
      fullPath: '/income/roi'
      preLoaderRoute: typeof AppIncomeRoiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/income/sp-profit': {
      id: '/_app/income/sp-profit'
      path: '/income/sp-profit'
      fullPath: '/income/sp-profit'
      preLoaderRoute: typeof AppIncomeSpProfitRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kyc/approved': {
      id: '/_app/kyc/approved'
      path: '/kyc/approved'
      fullPath: '/kyc/approved'
      preLoaderRoute: typeof AppKycApprovedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kyc/pending': {
      id: '/_app/kyc/pending'
      path: '/kyc/pending'
      fullPath: '/kyc/pending'
      preLoaderRoute: typeof AppKycPendingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kyc/rejected': {
      id: '/_app/kyc/rejected'
      path: '/kyc/rejected'
      fullPath: '/kyc/rejected'
      preLoaderRoute: typeof AppKycRejectedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/plans/direct': {
      id: '/_app/plans/direct'
      path: '/plans/direct'
      fullPath: '/plans/direct'
      preLoaderRoute: typeof AppPlansDirectRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/plans/performance': {
      id: '/_app/plans/performance'
      path: '/plans/performance'
      fullPath: '/plans/performance'
      preLoaderRoute: typeof AppPlansPerformanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/plans/rewards': {
      id: '/_app/plans/rewards'
      path: '/plans/rewards'
      fullPath: '/plans/rewards'
      preLoaderRoute: typeof AppPlansRewardsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rbac/audit': {
      id: '/_app/rbac/audit'
      path: '/rbac/audit'
      fullPath: '/rbac/audit'
      preLoaderRoute: typeof AppRbacAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rbac/profile': {
      id: '/_app/rbac/profile'
      path: '/rbac/profile'
      fullPath: '/rbac/profile'
      preLoaderRoute: typeof AppRbacProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rbac/roles': {
      id: '/_app/rbac/roles'
      path: '/rbac/roles'
      fullPath: '/rbac/roles'
      preLoaderRoute: typeof AppRbacRolesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rbac/staff': {
      id: '/_app/rbac/staff'
      path: '/rbac/staff'
      fullPath: '/rbac/staff'
      preLoaderRoute: typeof AppRbacStaffRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/help': {
      id: '/_app/settings/help'
      path: '/settings/help'
      fullPath: '/settings/help'
      preLoaderRoute: typeof AppSettingsHelpRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/news': {
      id: '/_app/settings/news'
      path: '/settings/news'
      fullPath: '/settings/news'
      preLoaderRoute: typeof AppSettingsNewsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/qr-wallet': {
      id: '/_app/settings/qr-wallet'
      path: '/settings/qr-wallet'
      fullPath: '/settings/qr-wallet'
      preLoaderRoute: typeof AppSettingsQrWalletRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/team/approvals': {
      id: '/_app/team/approvals'
      path: '/team/approvals'
      fullPath: '/team/approvals'
      preLoaderRoute: typeof AppTeamApprovalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users/$associateId': {
      id: '/_app/users/$associateId'
      path: '/users/$associateId'
      fullPath: '/users/$associateId'
      preLoaderRoute: typeof AppUsersAssociateIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users/active': {
      id: '/_app/users/active'
      path: '/users/active'
      fullPath: '/users/active'
      preLoaderRoute: typeof AppUsersActiveRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users/all': {
      id: '/_app/users/all'
      path: '/users/all'
      fullPath: '/users/all'
      preLoaderRoute: typeof AppUsersAllRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users/blocked': {
      id: '/_app/users/blocked'
      path: '/users/blocked'
      fullPath: '/users/blocked'
      preLoaderRoute: typeof AppUsersBlockedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users/inactive': {
      id: '/_app/users/inactive'
      path: '/users/inactive'
      fullPath: '/users/inactive'
      preLoaderRoute: typeof AppUsersInactiveRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users/levels': {
      id: '/_app/users/levels'
      path: '/users/levels'
      fullPath: '/users/levels'
      preLoaderRoute: typeof AppUsersLevelsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users/my': {
      id: '/_app/users/my'
      path: '/users/my'
      fullPath: '/users/my'
      preLoaderRoute: typeof AppUsersMyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users/rewards': {
      id: '/_app/users/rewards'
      path: '/users/rewards'
      fullPath: '/users/rewards'
      preLoaderRoute: typeof AppUsersRewardsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users/team': {
      id: '/_app/users/team'
      path: '/users/team'
      fullPath: '/users/team'
      preLoaderRoute: typeof AppUsersTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/withdraw/completed': {
      id: '/_app/withdraw/completed'
      path: '/withdraw/completed'
      fullPath: '/withdraw/completed'
      preLoaderRoute: typeof AppWithdrawCompletedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/withdraw/pending': {
      id: '/_app/withdraw/pending'
      path: '/withdraw/pending'
      fullPath: '/withdraw/pending'
      preLoaderRoute: typeof AppWithdrawPendingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/withdraw/rejected': {
      id: '/_app/withdraw/rejected'
      path: '/withdraw/rejected'
      fullPath: '/withdraw/rejected'
      preLoaderRoute: typeof AppWithdrawRejectedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users/team/': {
      id: '/_app/users/team/'
      path: '/'
      fullPath: '/users/team/'
      preLoaderRoute: typeof AppUsersTeamIndexRouteImport
      parentRoute: typeof AppUsersTeamRoute
    }
    '/_app/users/team/level/$level': {
      id: '/_app/users/team/level/$level'
      path: '/level/$level'
      fullPath: '/users/team/level/$level'
      preLoaderRoute: typeof AppUsersTeamLevelLevelRouteImport
      parentRoute: typeof AppUsersTeamRoute
    }
  }
}

interface AppGenealogyRouteChildren {
  AppGenealogyShiftRoute: typeof AppGenealogyShiftRoute
  AppGenealogyIndexRoute: typeof AppGenealogyIndexRoute
}

const AppGenealogyRouteChildren: AppGenealogyRouteChildren = {
  AppGenealogyShiftRoute: AppGenealogyShiftRoute,
  AppGenealogyIndexRoute: AppGenealogyIndexRoute,
}

const AppGenealogyRouteWithChildren = AppGenealogyRoute._addFileChildren(
  AppGenealogyRouteChildren,
)

interface AppUsersTeamRouteChildren {
  AppUsersTeamIndexRoute: typeof AppUsersTeamIndexRoute
  AppUsersTeamLevelLevelRoute: typeof AppUsersTeamLevelLevelRoute
}

const AppUsersTeamRouteChildren: AppUsersTeamRouteChildren = {
  AppUsersTeamIndexRoute: AppUsersTeamIndexRoute,
  AppUsersTeamLevelLevelRoute: AppUsersTeamLevelLevelRoute,
}

const AppUsersTeamRouteWithChildren = AppUsersTeamRoute._addFileChildren(
  AppUsersTeamRouteChildren,
)

interface AppRouteChildren {
  AppBusinessReportRoute: typeof AppBusinessReportRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppGenealogyRoute: typeof AppGenealogyRouteWithChildren
  AppKnowledgeRoute: typeof AppKnowledgeRoute
  AppDepositCompleteRoute: typeof AppDepositCompleteRoute
  AppDepositPendingRoute: typeof AppDepositPendingRoute
  AppDepositRejectedRoute: typeof AppDepositRejectedRoute
  AppFundAdminHistoryRoute: typeof AppFundAdminHistoryRoute
  AppFundTransferRoute: typeof AppFundTransferRoute
  AppFundUserHistoryRoute: typeof AppFundUserHistoryRoute
  AppFundWalletsRoute: typeof AppFundWalletsRoute
  AppIncomeAdminChargesRoute: typeof AppIncomeAdminChargesRoute
  AppIncomeReferralRoute: typeof AppIncomeReferralRoute
  AppIncomeRewardRoute: typeof AppIncomeRewardRoute
  AppIncomeRoiRoute: typeof AppIncomeRoiRoute
  AppIncomeSpProfitRoute: typeof AppIncomeSpProfitRoute
  AppKycApprovedRoute: typeof AppKycApprovedRoute
  AppKycPendingRoute: typeof AppKycPendingRoute
  AppKycRejectedRoute: typeof AppKycRejectedRoute
  AppPlansDirectRoute: typeof AppPlansDirectRoute
  AppPlansPerformanceRoute: typeof AppPlansPerformanceRoute
  AppPlansRewardsRoute: typeof AppPlansRewardsRoute
  AppRbacAuditRoute: typeof AppRbacAuditRoute
  AppRbacProfileRoute: typeof AppRbacProfileRoute
  AppRbacRolesRoute: typeof AppRbacRolesRoute
  AppRbacStaffRoute: typeof AppRbacStaffRoute
  AppSettingsHelpRoute: typeof AppSettingsHelpRoute
  AppSettingsNewsRoute: typeof AppSettingsNewsRoute
  AppSettingsQrWalletRoute: typeof AppSettingsQrWalletRoute
  AppTeamApprovalsRoute: typeof AppTeamApprovalsRoute
  AppUsersAssociateIdRoute: typeof AppUsersAssociateIdRoute
  AppUsersActiveRoute: typeof AppUsersActiveRoute
  AppUsersAllRoute: typeof AppUsersAllRoute
  AppUsersBlockedRoute: typeof AppUsersBlockedRoute
  AppUsersInactiveRoute: typeof AppUsersInactiveRoute
  AppUsersLevelsRoute: typeof AppUsersLevelsRoute
  AppUsersMyRoute: typeof AppUsersMyRoute
  AppUsersRewardsRoute: typeof AppUsersRewardsRoute
  AppUsersTeamRoute: typeof AppUsersTeamRouteWithChildren
  AppWithdrawCompletedRoute: typeof AppWithdrawCompletedRoute
  AppWithdrawPendingRoute: typeof AppWithdrawPendingRoute
  AppWithdrawRejectedRoute: typeof AppWithdrawRejectedRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBusinessReportRoute: AppBusinessReportRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppGenealogyRoute: AppGenealogyRouteWithChildren,
  AppKnowledgeRoute: AppKnowledgeRoute,
  AppDepositCompleteRoute: AppDepositCompleteRoute,
  AppDepositPendingRoute: AppDepositPendingRoute,
  AppDepositRejectedRoute: AppDepositRejectedRoute,
  AppFundAdminHistoryRoute: AppFundAdminHistoryRoute,
  AppFundTransferRoute: AppFundTransferRoute,
  AppFundUserHistoryRoute: AppFundUserHistoryRoute,
  AppFundWalletsRoute: AppFundWalletsRoute,
  AppIncomeAdminChargesRoute: AppIncomeAdminChargesRoute,
  AppIncomeReferralRoute: AppIncomeReferralRoute,
  AppIncomeRewardRoute: AppIncomeRewardRoute,
  AppIncomeRoiRoute: AppIncomeRoiRoute,
  AppIncomeSpProfitRoute: AppIncomeSpProfitRoute,
  AppKycApprovedRoute: AppKycApprovedRoute,
  AppKycPendingRoute: AppKycPendingRoute,
  AppKycRejectedRoute: AppKycRejectedRoute,
  AppPlansDirectRoute: AppPlansDirectRoute,
  AppPlansPerformanceRoute: AppPlansPerformanceRoute,
  AppPlansRewardsRoute: AppPlansRewardsRoute,
  AppRbacAuditRoute: AppRbacAuditRoute,
  AppRbacProfileRoute: AppRbacProfileRoute,
  AppRbacRolesRoute: AppRbacRolesRoute,
  AppRbacStaffRoute: AppRbacStaffRoute,
  AppSettingsHelpRoute: AppSettingsHelpRoute,
  AppSettingsNewsRoute: AppSettingsNewsRoute,
  AppSettingsQrWalletRoute: AppSettingsQrWalletRoute,
  AppTeamApprovalsRoute: AppTeamApprovalsRoute,
  AppUsersAssociateIdRoute: AppUsersAssociateIdRoute,
  AppUsersActiveRoute: AppUsersActiveRoute,
  AppUsersAllRoute: AppUsersAllRoute,
  AppUsersBlockedRoute: AppUsersBlockedRoute,
  AppUsersInactiveRoute: AppUsersInactiveRoute,
  AppUsersLevelsRoute: AppUsersLevelsRoute,
  AppUsersMyRoute: AppUsersMyRoute,
  AppUsersRewardsRoute: AppUsersRewardsRoute,
  AppUsersTeamRoute: AppUsersTeamRouteWithChildren,
  AppWithdrawCompletedRoute: AppWithdrawCompletedRoute,
  AppWithdrawPendingRoute: AppWithdrawPendingRoute,
  AppWithdrawRejectedRoute: AppWithdrawRejectedRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  PartnerRoute: PartnerRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
