# Generated by Django 5.2.16 on 2026-07-25 19:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('associates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GenealogyClosure',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('depth', models.PositiveIntegerField(db_index=True)),
                ('ancestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descendant_links', to='associates.associate')),
                ('descendant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ancestor_links', to='associates.associate')),
            ],
            options={
                'indexes': [models.Index(fields=['ancestor', 'depth'], name='genealogy_g_ancesto_8d6bbc_idx'), models.Index(fields=['descendant', 'depth'], name='genealogy_g_descend_9d77ac_idx')],
                'unique_together': {('ancestor', 'descendant')},
            },
        ),
        migrations.CreateModel(
            name='GenealogyNode',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('path', models.TextField(db_index=True, help_text='Materialized path e.g. /root/uuid/uuid/')),
                ('depth', models.PositiveIntegerField(db_index=True, default=0)),
                ('leg_index', models.PositiveIntegerField(default=0)),
                ('associate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='genealogy_node', to='associates.associate')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='genealogy.genealogynode')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['path'], name='genealogy_g_path_ad8b6d_idx'), models.Index(fields=['parent', 'leg_index'], name='genealogy_g_parent__76b58e_idx')],
            },
        ),
    ]
