# Generated by Django 5.2.17 on 2026-08-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='wallet_type',
            field=models.CharField(choices=[('main', 'Main Fund'), ('personal', 'Personal Fund'), ('income', 'Income Wallet'), ('reward', 'Reward Wallet'), ('roi', 'ROI Wallet'), ('withdraw', 'Withdraw Wallet')], max_length=20),
        ),
    ]
